<a href="https://colab.research.google.com/github/UdayLab/PAMI/blob/main/notebooks/extras/DF2DB/denseFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Converting a DataFrame in Dense Format to a different Database types
> Illustration with 5-year nation-wide air pollution data of Japan

## Introduction

*   A transactional database is a collection of transactions. Every transaction constitutes of a transaction-identifier (TID) and a set of items.

*   A temporal database is a collection of transactions ordered by their timestamp.

*   A timeseries represents an ordered collection of values of an event (or item) over time. A multiple timeseries represents the collection of multiple timeseries gathered from multiple items over a particular duration.

*   A utility transactional database consists of a transactional identifier (tid), items, and their corresponding utility values in a transaction.

*   We use the 5-year nation-wide air pollution (PM2.5) data of Japan for illustration purposes.

### Step 1: Download the air pollution dataset [1]

In [1]:
!wget https://www.dropbox.com/s/wa8d1sujzlx56hh/ETL_DATA_new.csv

--2023-11-23 10:13:05--  https://www.dropbox.com/s/wa8d1sujzlx56hh/ETL_DATA_new.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.8.18, 2620:100:6018:18::a27d:312
Connecting to www.dropbox.com (www.dropbox.com)|162.125.8.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/wa8d1sujzlx56hh/ETL_DATA_new.csv [following]
--2023-11-23 10:13:05--  https://www.dropbox.com/s/raw/wa8d1sujzlx56hh/ETL_DATA_new.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uce1b2461624b1b14ffcf9dcf9f5.dl.dropboxusercontent.com/cd/0/inline/CIETqukmvN_OMpM_XSP3PJNQPKIM1avP3OzzFP4vn5rxhbzDc-16UV1ul1IXwNLjuEdbVcb_o6QXUsiU-gKIGWtojpul99aXLYox0hJqcurccoEr3F0M7WqqGO-lfoF4UZeSmxU4nNZrMkQn3SpqnFsx/file# [following]
--2023-11-23 10:13:05--  https://uce1b2461624b1b14ffcf9dcf9f5.dl.dropboxusercontent.com/cd/0/inline/CIETqukmvN_OMpM_XSP3PJNQPKIM1avP3OzzFP4vn5rxhbzDc-16UV1ul1IXwNLjuEdbVcb_o6QXUsiU-gKIGWtojpul99aXLYox0hJqcurccoEr3F0M7WqqGO-lfoF4UZeSmxU4nNZrMkQn3SpqnFsx/file
Resolving uce1b2461624b1b14ffcf9dcf9f5.dl.dropboxusercontent.com (uce1b2461624b1b14ffcf9dcf9f5.dl.dropboxusercontent.com)... 162.125.8.15, 2620:100:6019:15::a27d:40f
Connecting to uce1b2461624b1b14ffcf9dcf9f5.dl.dropboxusercontent.com (uce1b2461624b1b14ffcf9dcf9f5.dl.dropboxusercontent.com)|162.125.8.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 262918270 (251M) [text/plain]
Saving to: ‘ETL_DATA_new.csv.1’

ETL_DATA_new.csv.1  100%[===================>] 250.74M   167MB/s    in 1.5s

2023-11-23 10:13:07 (167 MB/s) - ‘ETL_DATA_new.csv.1’ saved [262918270/262918270]

### Step 2: Read the dataset and analyze it

In [2]:
import pandas as pd
dataset = pd.read_csv('ETL_DATA_new.csv', index_col=0)

dataset
# you can notice that dataset is collected from 2018-01-01 01:00:00 hours to 2023-04-25 22:00:00 hours (5+ years)

,TimeStamp,Point(139.0794379 36.3727776),Point(139.1051411 36.3963822),Point(139.0960211 36.4047323),Point(139.0428727 36.3816035),Point(138.9955116 36.33801589999999),Point(139.342672 36.4105658),Point(139.3526243 36.3695416),Point(139.1945766 36.31351160000001),Point(139.2076974 36.3034767),...,Point(139.9418164 36.7656467),Point(140.0549894 36.9688923),Point(139.8775674 36.3847082),Point(139.9101767 36.4393022),Point(139.9074816 36.4445767),Point(140.0934838 36.4673588),Point(139.7422865 36.2305774),Point(139.7151723 36.822353),Point(140.1510903 36.6598314),Unnamed: 1832
,,,,,,,,,,,,,,,,,,,,,
0,2018-01-01 01:00:00,NaN,NaN,5.0,13.0,18.0,20.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,4.0,NaN
1,2018-01-01 02:00:00,NaN,NaN,11.0,12.0,22.0,15.0,NaN,NaN,NaN,...,NaN,6.0,NaN,NaN,NaN,9.0,NaN,NaN,5.0,NaN
2,2018-01-01 03:00:00,NaN,NaN,7.0,12.0,19.0,16.0,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,10.0,NaN,NaN,6.0,NaN
3,2018-01-01 04:00:00,NaN,NaN,5.0,11.0,16.0,11.0,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,11.0,NaN,NaN,11.0,NaN
4,2018-01-01 05:00:00,NaN,NaN,6.0,11.0,10.0,8.0,NaN,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,8.0,NaN,NaN,6.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46000,2023-04-25 18:00:00,NaN,NaN,NaN,22.0,3.0,15.0,NaN,NaN,NaN,...,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN
46001,2023-04-25 19:00:00,NaN,NaN,NaN,21.0,2.0,19.0,NaN,NaN,NaN,...,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN
46002,2023-04-25 20:00:00,NaN,NaN,NaN,20.0,10.0,19.0,NaN,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN
46003,2023-04-25 21:00:00,NaN,NaN,NaN,19.0,2.0,15.0,NaN,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN
46004,2023-04-25 22:00:00,NaN,NaN,NaN,19.0,1.0,17.0,NaN,NaN,NaN,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN

__Format of the dataset:__ timestamp _tabSpace_ sensorLocation1 _tabSpace_ sensorLocation2 _tabSpace_ ... _tabSpace_ sensorLocation

### Step 3: Preprocessing the dataset

#### Step 3.1: Removing the timestamp column

In [3]:
dataset.drop('TimeStamp', inplace=True, axis=1)
dataset

,Point(139.0794379 36.3727776),Point(139.1051411 36.3963822),Point(139.0960211 36.4047323),Point(139.0428727 36.3816035),Point(138.9955116 36.33801589999999),Point(139.342672 36.4105658),Point(139.3526243 36.3695416),Point(139.1945766 36.31351160000001),Point(139.2076974 36.3034767),Point(139.3817322 36.2909131),...,Point(139.9418164 36.7656467),Point(140.0549894 36.9688923),Point(139.8775674 36.3847082),Point(139.9101767 36.4393022),Point(139.9074816 36.4445767),Point(140.0934838 36.4673588),Point(139.7422865 36.2305774),Point(139.7151723 36.822353),Point(140.1510903 36.6598314),Unnamed: 1832
,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,5.0,13.0,18.0,20.0,NaN,NaN,NaN,23.0,...,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,4.0,NaN
1,NaN,NaN,11.0,12.0,22.0,15.0,NaN,NaN,NaN,32.0,...,NaN,6.0,NaN,NaN,NaN,9.0,NaN,NaN,5.0,NaN
2,NaN,NaN,7.0,12.0,19.0,16.0,NaN,NaN,NaN,32.0,...,NaN,0.0,NaN,NaN,NaN,10.0,NaN,NaN,6.0,NaN
3,NaN,NaN,5.0,11.0,16.0,11.0,NaN,NaN,NaN,28.0,...,NaN,2.0,NaN,NaN,NaN,11.0,NaN,NaN,11.0,NaN
4,NaN,NaN,6.0,11.0,10.0,8.0,NaN,NaN,NaN,27.0,...,NaN,4.0,NaN,NaN,NaN,8.0,NaN,NaN,6.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46000,NaN,NaN,NaN,22.0,3.0,15.0,NaN,NaN,NaN,16.0,...,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN
46001,NaN,NaN,NaN,21.0,2.0,19.0,NaN,NaN,NaN,14.0,...,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN
46002,NaN,NaN,NaN,20.0,10.0,19.0,NaN,NaN,NaN,13.0,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN
46003,NaN,NaN,NaN,19.0,2.0,15.0,NaN,NaN,NaN,10.0,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN
46004,NaN,NaN,NaN,19.0,1.0,17.0,NaN,NaN,NaN,13.0,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN

#### Step 3.2: Removing Sensors that do not have Point information

In [4]:
sensorsWithPointInformation = [col for col in dataset if 'Unnamed' in col]
dataset.drop(columns=sensorsWithPointInformation, inplace=True, axis=1)
dataset.head()

,Point(139.0794379 36.3727776),Point(139.1051411 36.3963822),Point(139.0960211 36.4047323),Point(139.0428727 36.3816035),Point(138.9955116 36.33801589999999),Point(139.342672 36.4105658),Point(139.3526243 36.3695416),Point(139.1945766 36.31351160000001),Point(139.2076974 36.3034767),Point(139.3817322 36.2909131),...,Point(139.9239959 36.8062129),Point(139.9418164 36.7656467),Point(140.0549894 36.9688923),Point(139.8775674 36.3847082),Point(139.9101767 36.4393022),Point(139.9074816 36.4445767),Point(140.0934838 36.4673588),Point(139.7422865 36.2305774),Point(139.7151723 36.822353),Point(140.1510903 36.6598314)
,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,5.0,13.0,18.0,20.0,NaN,NaN,NaN,23.0,...,1.0,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,4.0
1,NaN,NaN,11.0,12.0,22.0,15.0,NaN,NaN,NaN,32.0,...,0.0,NaN,6.0,NaN,NaN,NaN,9.0,NaN,NaN,5.0
2,NaN,NaN,7.0,12.0,19.0,16.0,NaN,NaN,NaN,32.0,...,2.0,NaN,0.0,NaN,NaN,NaN,10.0,NaN,NaN,6.0
3,NaN,NaN,5.0,11.0,16.0,11.0,NaN,NaN,NaN,28.0,...,3.0,NaN,2.0,NaN,NaN,NaN,11.0,NaN,NaN,11.0
4,NaN,NaN,6.0,11.0,10.0,8.0,NaN,NaN,NaN,27.0,...,5.0,NaN,4.0,NaN,NaN,NaN,8.0,NaN,NaN,6.0

#### Step 3.3: Fillup the missing values (NaN) with zero

In [5]:
dataset = dataset.fillna(0)
dataset.head()

,Point(139.0794379 36.3727776),Point(139.1051411 36.3963822),Point(139.0960211 36.4047323),Point(139.0428727 36.3816035),Point(138.9955116 36.33801589999999),Point(139.342672 36.4105658),Point(139.3526243 36.3695416),Point(139.1945766 36.31351160000001),Point(139.2076974 36.3034767),Point(139.3817322 36.2909131),...,Point(139.9239959 36.8062129),Point(139.9418164 36.7656467),Point(140.0549894 36.9688923),Point(139.8775674 36.3847082),Point(139.9101767 36.4393022),Point(139.9074816 36.4445767),Point(140.0934838 36.4673588),Point(139.7422865 36.2305774),Point(139.7151723 36.822353),Point(140.1510903 36.6598314)
,,,,,,,,,,,,,,,,,,,,,
0,0.0,0.0,5.0,13.0,18.0,20.0,0.0,0.0,0.0,23.0,...,1.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,4.0
1,0.0,0.0,11.0,12.0,22.0,15.0,0.0,0.0,0.0,32.0,...,0.0,0.0,6.0,0.0,0.0,0.0,9.0,0.0,0.0,5.0
2,0.0,0.0,7.0,12.0,19.0,16.0,0.0,0.0,0.0,32.0,...,2.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,6.0
3,0.0,0.0,5.0,11.0,16.0,11.0,0.0,0.0,0.0,28.0,...,3.0,0.0,2.0,0.0,0.0,0.0,11.0,0.0,0.0,11.0
4,0.0,0.0,6.0,11.0,10.0,8.0,0.0,0.0,0.0,27.0,...,5.0,0.0,4.0,0.0,0.0,0.0,8.0,0.0,0.0,6.0

#### Step 3.4: Removing abnormal values in the data

In [6]:
dataset.where(dataset <= 250, 0, inplace=True) #Set PM2.5 values greater than 250 to 0.
dataset.where(dataset > 0, 0, inplace=True)    #Set PM2.5 values less than 0 to 0
dataset

,Point(139.0794379 36.3727776),Point(139.1051411 36.3963822),Point(139.0960211 36.4047323),Point(139.0428727 36.3816035),Point(138.9955116 36.33801589999999),Point(139.342672 36.4105658),Point(139.3526243 36.3695416),Point(139.1945766 36.31351160000001),Point(139.2076974 36.3034767),Point(139.3817322 36.2909131),...,Point(139.9239959 36.8062129),Point(139.9418164 36.7656467),Point(140.0549894 36.9688923),Point(139.8775674 36.3847082),Point(139.9101767 36.4393022),Point(139.9074816 36.4445767),Point(140.0934838 36.4673588),Point(139.7422865 36.2305774),Point(139.7151723 36.822353),Point(140.1510903 36.6598314)
,,,,,,,,,,,,,,,,,,,,,
0,0.0,0.0,5.0,13.0,18.0,20.0,0.0,0.0,0.0,23.0,...,1.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,4.0
1,0.0,0.0,11.0,12.0,22.0,15.0,0.0,0.0,0.0,32.0,...,0.0,0.0,6.0,0.0,0.0,0.0,9.0,0.0,0.0,5.0
2,0.0,0.0,7.0,12.0,19.0,16.0,0.0,0.0,0.0,32.0,...,2.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,6.0
3,0.0,0.0,5.0,11.0,16.0,11.0,0.0,0.0,0.0,28.0,...,3.0,0.0,2.0,0.0,0.0,0.0,11.0,0.0,0.0,11.0
4,0.0,0.0,6.0,11.0,10.0,8.0,0.0,0.0,0.0,27.0,...,5.0,0.0,4.0,0.0,0.0,0.0,8.0,0.0,0.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46000,0.0,0.0,0.0,22.0,3.0,15.0,0.0,0.0,0.0,16.0,...,12.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
46001,0.0,0.0,0.0,21.0,2.0,19.0,0.0,0.0,0.0,14.0,...,11.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
46002,0.0,0.0,0.0,20.0,10.0,19.0,0.0,0.0,0.0,13.0,...,11.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
46003,0.0,0.0,0.0,19.0,2.0,15.0,0.0,0.0,0.0,10.0,...,10.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
46004,0.0,0.0,0.0,19.0,1.0,17.0,0.0,0.0,0.0,13.0,...,9.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0

### Step 4: Installing the latest version of PAMI package

In [7]:
!pip install -U pami

Requirement already satisfied: pami in /usr/local/lib/python3.10/dist-packages (2023.11.23.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from pami) (5.9.5)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pami) (1.5.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from pami) (5.15.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from pami) (3.7.1)
Requirement already satisfied: resource in /usr/local/lib/python3.10/dist-packages (from pami) (0.2.1)
Requirement already satisfied: validators in /usr/local/lib/python3.10/dist-packages (from pami) (0.22.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from pami) (2.0.7)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from pami) (9.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from pami) (1.23.5)
Requirement already satisfied: sphinx-rtd-theme in /usr/local/lib/python3.10/dist-packages (from pami) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pami) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pami) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pami) (4.44.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pami) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pami) (23.2)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pami) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib->pami) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pami) (2023.3.post1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->pami) (8.2.3)
Requirement already satisfied: JsonForm>=0.0.2 in /usr/local/lib/python3.10/dist-packages (from resource->pami) (0.0.2)
Requirement already satisfied: JsonSir>=0.0.2 in /usr/local/lib/python3.10/dist-packages (from resource->pami) (0.0.2)
Requirement already satisfied: python-easyconfig>=0.1.0 in /usr/local/lib/python3.10/dist-packages (from resource->pami) (0.1.7)
Requirement already satisfied: sphinx<8,>=1.6 in /usr/local/lib/python3.10/dist-packages (from sphinx-rtd-theme->pami) (5.0.2)
Requirement already satisfied: docutils<0.19 in /usr/local/lib/python3.10/dist-packages (from sphinx-rtd-theme->pami) (0.18.1)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in /usr/local/lib/python3.10/dist-packages (from sphinx-rtd-theme->pami) (4.1)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.10/dist-packages (from JsonForm>=0.0.2->resource->pami) (4.19.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib->pami) (1.16.0)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from python-easyconfig>=0.1.0->resource->pami) (6.0.1)
Requirement already satisfied: sphinxcontrib-applehelp in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (1.0.7)
Requirement already satisfied: sphinxcontrib-devhelp in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (1.0.5)
Requirement already satisfied: sphinxcontrib-jsmath in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (2.0.4)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.5 in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (1.1.9)
Requirement already satisfied: sphinxcontrib-qthelp in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (1.0.6)
Requirement already satisfied: Jinja2>=2.3 in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (3.1.2)
Requirement already satisfied: Pygments>=2.0 in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (2.16.1)
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (2.2.0)
Requirement already satisfied: babel>=1.3 in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (2.13.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (0.7.13)
Requirement already satisfied: imagesize in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (1.4.1)
Requirement already satisfied: requests>=2.5.0 in /usr/local/lib/python3.10/dist-packages (from sphinx<8,>=1.6->sphinx-rtd-theme->pami) (2.31.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=2.3->sphinx<8,>=1.6->sphinx-rtd-theme->pami) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.5.0->sphinx<8,>=1.6->sphinx-rtd-theme->pami) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.5.0->sphinx<8,>=1.6->sphinx-rtd-theme->pami) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.5.0->sphinx<8,>=1.6->sphinx-rtd-theme->pami) (2023.7.22)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.10/dist-packages (from jsonschema->JsonForm>=0.0.2->resource->pami) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema->JsonForm>=0.0.2->resource->pami) (2023.11.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema->JsonForm>=0.0.2->resource->pami) (0.31.0)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema->JsonForm>=0.0.2->resource->pami) (0.13.0)

### Step 5: Converting the data frame into a transactional database

In [8]:
from PAMI.extras.DF2DB import DenseFormatDF as dense
obj = dense.DenseFormatDF(dataset)

obj.convert2TransactionalDatabase('PM24HeavyPollutionRecordingSensors.csv','>=',35)

### Step 6: Printing the transactional database.

In [9]:
!head -3 PM24HeavyPollutionRecordingSensors.csv

Point(139.750635 35.7977241)	Point(139.8841693 35.8422674)	Point(139.3819898 36.2229999)	Point(139.9206727 35.684037)	Point(139.9785953 35.6880639)	Point(139.9033705 35.7876179)	Point(139.9123927 35.7995549)	Point(139.880097 35.953403)	Point(139.9035901 35.8570293)	Point(139.9012134 35.6552406)	Point(139.8356927 35.6967785)	Point(139.7209595 35.6108138)	Point(139.7054233 35.7609043)	Point(139.8257782 35.7697167)	Point(139.8045157 35.77453510000001)	Point(139.8692678 35.7864558)	Point(139.8530976 35.7608755)	Point(139.8773135 35.6821907)	Point(137.1418898 34.9626945)	Point(136.8905668 35.0122987)	Point(136.6548337 35.0051925)	Point(139.4949175 36.2914457)
Point(139.7962265 35.8959041)	Point(139.8841693 35.8422674)	Point(139.3819898 36.2229999)	Point(139.9206727 35.684037)	Point(139.9785953 35.6880639)	Point(139.9033705 35.7876179)	Point(139.9123927 35.7995549)	Point(139.880097 35.953403)	Point(139.9012134 35.6552406)	Point(139.8276492 35.689975)	Point(139.8356927 35.6967785)	Point(139.7054233 35.7609043)	Point(139.8257782 35.7697167)	Point(139.8045157 35.77453510000001)	Point(139.8776074 35.744251)	Point(139.8692678 35.7864558)	Point(139.8530976 35.7608755)	Point(139.8859668 35.7099429)	Point(139.8773135 35.6821907)	Point(139.5257126 35.3986601)	Point(139.4898296 35.425629)	Point(139.6704215 35.2829123)	Point(138.3366179 34.9856239)	Point(136.8880309 35.1033076)	Point(137.1882268 34.9467181)	Point(137.1418898 34.9626945)	Point(136.9121266 35.0427414)	Point(130.1948336 32.4611967)
Point(139.8841693 35.8422674)	Point(140.067069 35.6445893)	Point(139.9785953 35.6880639)	Point(139.9033705 35.7876179)	Point(139.9123927 35.7995549)	Point(140.0679921 35.5260141)	Point(139.9012134 35.6552406)	Point(139.8276492 35.689975)	Point(139.8356927 35.6967785)	Point(139.7054233 35.7609043)	Point(139.5990181 35.7377286)	Point(139.8257782 35.7697167)	Point(139.8045157 35.77453510000001)	Point(139.8776074 35.744251)	Point(139.8692678 35.7864558)	Point(139.8530976 35.7608755)	Point(139.8859668 35.7099429)	Point(139.8773135 35.6821907)	Point(139.871021 35.6536708)	Point(130.1948336 32.4611967)	Point(140.5167529 36.1595964)

**Format:** Item1 Item2 Item3 Item4 ...

### Step 7: Converting the data frame into a temporal database

In [10]:
obj.convert2TemporalDatabase('PM25_heavyPollution_temporalDatabase.csv','>=',35)

### Step 8: Printing the temporal database

In [11]:
!head -3 PM25_heavyPollution_temporalDatabase.csv

1	Point(139.750635 35.7977241)	Point(139.8841693 35.8422674)	Point(139.3819898 36.2229999)	Point(139.9206727 35.684037)	Point(139.9785953 35.6880639)	Point(139.9033705 35.7876179)	Point(139.9123927 35.7995549)	Point(139.880097 35.953403)	Point(139.9035901 35.8570293)	Point(139.9012134 35.6552406)	Point(139.8356927 35.6967785)	Point(139.7209595 35.6108138)	Point(139.7054233 35.7609043)	Point(139.8257782 35.7697167)	Point(139.8045157 35.77453510000001)	Point(139.8692678 35.7864558)	Point(139.8530976 35.7608755)	Point(139.8773135 35.6821907)	Point(137.1418898 34.9626945)	Point(136.8905668 35.0122987)	Point(136.6548337 35.0051925)	Point(139.4949175 36.2914457)
2	Point(139.7962265 35.8959041)	Point(139.8841693 35.8422674)	Point(139.3819898 36.2229999)	Point(139.9206727 35.684037)	Point(139.9785953 35.6880639)	Point(139.9033705 35.7876179)	Point(139.9123927 35.7995549)	Point(139.880097 35.953403)	Point(139.9012134 35.6552406)	Point(139.8276492 35.689975)	Point(139.8356927 35.6967785)	Point(139.7054233 35.7609043)	Point(139.8257782 35.7697167)	Point(139.8045157 35.77453510000001)	Point(139.8776074 35.744251)	Point(139.8692678 35.7864558)	Point(139.8530976 35.7608755)	Point(139.8859668 35.7099429)	Point(139.8773135 35.6821907)	Point(139.5257126 35.3986601)	Point(139.4898296 35.425629)	Point(139.6704215 35.2829123)	Point(138.3366179 34.9856239)	Point(136.8880309 35.1033076)	Point(137.1882268 34.9467181)	Point(137.1418898 34.9626945)	Point(136.9121266 35.0427414)	Point(130.1948336 32.4611967)
3	Point(139.8841693 35.8422674)	Point(140.067069 35.6445893)	Point(139.9785953 35.6880639)	Point(139.9033705 35.7876179)	Point(139.9123927 35.7995549)	Point(140.0679921 35.5260141)	Point(139.9012134 35.6552406)	Point(139.8276492 35.689975)	Point(139.8356927 35.6967785)	Point(139.7054233 35.7609043)	Point(139.5990181 35.7377286)	Point(139.8257782 35.7697167)	Point(139.8045157 35.77453510000001)	Point(139.8776074 35.744251)	Point(139.8692678 35.7864558)	Point(139.8530976 35.7608755)	Point(139.8859668 35.7099429)	Point(139.8773135 35.6821907)	Point(139.871021 35.6536708)	Point(130.1948336 32.4611967)	Point(140.5167529 36.1595964)

**Format:** timestamp Item1 Item2 Item3 Item4